### PR TITLE
fix(chat): Call `check_echo()` in `chat()` for consistent echo behavior

### LINKED ISSUE #741: `chat()` ends up with a different default value for `echo` than direct chat functions
```r
library(ellmer)

chat("openai")$chat("Hi there") # doesn't stream (echo="none")
chat_openai()$chat("Hi there") # streams (echo="output")
```

This happens because the default value for `echo` is decided according to where the function is called. Because we call `chat_openai()` _inside_ `chat()` we lose the default value.

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #741

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -67,7 +67,7 @@ prettify <- function(x) {
   )
 }
 
-check_echo <- function(echo = NULL) {
+check_echo <- function(echo = NULL, .envir = NULL) {
```
Comment (hadley) [inline R/utils.R]: I think this is remnants of a previous approach

**Review by hadley — APPROVED** [review]
